# Generated by Django 3.2.5 on 2021-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lemail', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('cpassword', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='submit',
            name='number',
            field=models.IntegerField(),
        ),
    ]
