# Generated by Django 3.2.5 on 2021-08-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210805_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lemail',
            new_name='lname',
        ),
    ]
